version: "3.9"
services:
  mqtt_broker:
    build: .
    ports:
      - "9084:9084"
      - "4000:443"
    volumes:
      - ./mqtt_broker_mount/:/root/proiect/
    tty: true
    stdin_open: true

  device:
    build: .
    ports:
      - "9085:9085"
      - "4001:443"
    volumes:
      - ./device_mount/:/root/proiect/
    tty: true
    stdin_open: true

  device2:
    build: .
    ports:
      - "9086:9086"
      - "4002:443"
    volumes:
      - ./device_mount:/root/proiect/
    tty: true
    stdin_open: true
